### ISSUE TITLE
Please add a FAQ to the documentation

### ISSUE THREAD

**Issue by marcelinorc** [t4ngo/dragonfly#37]
I can suggest starting with this question:

http://stackoverflow.com/questions/22410020/does-dragonfly-use-the-given-grammar-context-to-improve-recognition/22420235?noredirect=1#comment45743940_22420235

**Comment by t4ngo** [comment]
Stackoverflow is itself a great place for frequently asked questions, especially because it provides the means for community discussions and question ranking. Given that Dragonfly has its own Stackoverflow tag "python-dragonfly", it's easy to link to relevant questions. I added links from Dragonfly's readme and docs in commit aa1455ec71ea47d006370445610b12371e5039bc.

**Comment by marcelinorc** [comment]
Thanks, keep up! I love DragonFly
